"use client";

import Link from "next/link";
import { useSession } from "@/lib/auth-client";
import { useRouter } from "next/navigation";
import { useEffect } from "react";

export default function LandingPage() {
  const { data: session, isPending } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (!isPending && session) {
      router.push("/dashboard");
    }
  }, [session, isPending, router]);

  if (isPending) return null;

  return (
    <div className="flex flex-col items-center animate-in fade-in duration-700 pb-20">
      {/* Hero Section */}
      <section className="w-full py-20 lg:py-32 flex flex-col items-center text-center relative overflow-hidden">
        {/* Background glow */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-blue-600/20 rounded-full blur-[120px] -z-10 pointer-events-none" />
        
        <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center text-white font-bold text-2xl shadow-xl shadow-blue-500/20 mb-8 ring-4 ring-gray-900">
          SP
        </div>
        
        <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-white to-gray-400 mb-6 max-w-4xl">
          Smarter Trading with AI Intelligence
        </h1>
        
        <p className="text-lg md:text-xl text-gray-400 max-w-2xl mb-10 leading-relaxed">
          Unlock institutional-grade insights. Our Stock Market Price Predictor uses deep learning (LSTM) and a multi-agent framework to give you the edge.
        </p>
        
        <div className="flex flex-col sm:flex-row gap-4 w-full sm:w-auto z-10">
          <Link href="/sign-up" className="px-8 py-4 rounded-xl bg-white text-black font-semibold hover:bg-gray-200 transition-colors shadow-[0_0_40px_rgba(255,255,255,0.1)] flex items-center justify-center gap-2">
            Start Predicting for Free
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14 5l7 7m0 0l-7 7m7-7H3" /></svg>
          </Link>
          <Link href="/sign-in" className="px-8 py-4 rounded-xl bg-gray-900 border border-gray-700 text-white font-semibold hover:bg-gray-800 transition-colors flex items-center justify-center">
            Sign In
          </Link>
        </div>
      </section>

      {/* Features Section */}
      <section className="w-full py-20 border-t border-gray-800/50 mt-10">
        <h2 className="text-3xl font-bold text-center mb-16">The Ultimate Trading Arsenal</h2>
        
        <div className="grid md:grid-cols-3 gap-8 max-w-6xl mx-auto px-4">
          <div className="p-8 rounded-3xl bg-gray-900/40 border border-gray-800 hover:border-gray-700 transition-colors shadow-2xl backdrop-blur-sm">
            <div className="w-14 h-14 rounded-2xl bg-blue-500/20 flex items-center justify-center text-2xl mb-6 shadow-inner shadow-blue-500/10">📈</div>
            <h3 className="text-xl font-semibold mb-3">LSTM Deep Learning</h3>
            <p className="text-gray-400 leading-relaxed">Our neural networks analyze years of historical OHLCV data to forecast price action with mathematical precision.</p>
          </div>
          
          <div className="p-8 rounded-3xl bg-gray-900/40 border border-gray-800 hover:border-gray-700 transition-colors shadow-2xl backdrop-blur-sm">
            <div className="w-14 h-14 rounded-2xl bg-purple-500/20 flex items-center justify-center text-2xl mb-6 shadow-inner shadow-purple-500/10">🤖</div>
            <h3 className="text-xl font-semibold mb-3">Multi-Agent Reports</h3>
            <p className="text-gray-400 leading-relaxed">Get human-readable briefings generated by an ensemble of AI "agents" acting as technical and fundamental analysts.</p>
          </div>

          <div className="p-8 rounded-3xl bg-gray-900/40 border border-gray-800 hover:border-gray-700 transition-colors shadow-2xl backdrop-blur-sm">
            <div className="w-14 h-14 rounded-2xl bg-green-500/20 flex items-center justify-center text-2xl mb-6 shadow-inner shadow-green-500/10">📊</div>
            <h3 className="text-xl font-semibold mb-3">Advanced Charting</h3>
            <p className="text-gray-400 leading-relaxed">Interactive TradingView charts, Bollinger Bands, SMA overlays, and AI-detected volume spikes built right in.</p>
          </div>
        </div>
      </section>
    </div>
  );
}
